version: '3'
services:
  neo4j:
    image: neo4j
    hostname: neo4j
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/mnt/d/Projects/github/graph_ql_challenge/Data